### ISSUE TITLE
platform.txt from core 'XInput AVR Boards' contains deprecated compiler.path

### ISSUE THREAD

**Issue by eadmaster** [dmadison/ArduinoXInput_AVR#20]
When uploading [this sketch](https://github.com/dmadison/ArduinoXInput/blob/master/examples/GamepadPins/GamepadPins.ino) via Arduino IDE v1.8.19 on Ubuntu 22.04:

````
Arduino: 1.8.19 (Linux), Board: "Arduino Leonardo w/ XInput"

Warning: platform.txt from core 'XInput AVR Boards' contains deprecated compiler.path={runtime.tools.avr-gcc.path}/bin/, automatically converted to compiler.path=/usr/bin/. Consider upgrading this core.
Archiving built core (caching) in: /tmp/arduino_cache_537510/core/core_xinput_avr_leonardo_274ee2d9d7d3efc61d557bfcd901d641.a
Sketch uses 4656 bytes (16%) of program storage space. Maximum is 28672 bytes.
Global variables use 150 bytes (5%) of dynamic memory, leaving 2410 bytes for local variables. Maximum is 2560 bytes.
java.io.IOException: Cannot run program "___REMOVE___/bin/avrdude": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at java.base/java.lang.Runtime.exec(Runtime.java:451)
	at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:11)
	at cc.arduino.packages.Uploader.executeUploadCommand(Uploader.java:129)
	at cc.arduino.packages.uploaders.SerialUploader.runCommand(SerialUploader.java:383)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:197)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:77)
	at processing.app.SketchController.upload(SketchController.java:732)
	at processing.app.SketchController.exportApplet(SketchController.java:703)
	at processing.app.Editor$UploadHandler.run(Editor.java:2061)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 12 more
An error occurred while uploading the sketch


This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`````

**Comment by eadmaster** [comment]
fixed by updating to the latest arduino ide
